### ISSUE TITLE
Table Checklist

### ISSUE THREAD

**Issue by embray** [spacetelescope/PyFITS#15]
This is an overview of things that need to be done and issues that need to be fixed in the process of overhauling the Table interface.

(the text of this issue is a WIP)
- [ ] The Astropy table sub-package needs to be backported into PyFITS to start with.  This will probably drop support for a few features specific to Astropy, such as Units and color printing.  Later, when this work is merged into Astropy, it will be natural to add Units support back on.
- [ ] FITS tables should be able to handle duplicate column names (though it should warn against them). See https://trac.assembla.com/pyfits/ticket/191  (this could be handled in a manner similar to duplicate keywords in headers)
- [ ] When creating a new Column from an existing array or list, make sure the shape of the input data is sensible for the shape of the column (taking into account the repeat count of the data format and the TDIM keyword).  Make sure also that the data type either matches up or can be converted to the correct type. (See https://trac.assembla.com/pyfits/ticket/212). I think the Astropy Column class will already mostly handle this, though some FITS-specific extensions may be required.
- [ ] It needs to be possible to read data in a memory-efficient manner of large columns that require the data to be converted from the on-disk format to some other representation (see for example https://trac.assembla.com/pyfits/ticket/33, though it would be nice to do this without a separate "sections" interface).  This might be very tricky, however.
- [ ] Users should create new table data through the `Table` class and `Column` class (or some FITS-specific subclass thereof).  They can then pass that data in to the `BinTableHDU` and `TableHDU` constructors to create the appropriate HDUs.  Those constructors would be responsible for informing the user whether the table data can actually be serialized in that format.  This is especially relevant when creating an ASCII table (`TableHDU`) as it supports a much more limited range of data types. (see https://trac.assembla.com/pyfits/ticket/60)
- [ ] Table columns should support optional recognition of unsigned integers in addition to the usual tscal/tzero support (see https://trac.assembla.com/pyfits/ticket/192)--preliminary support for this is implemented in astropy/astropy#362, but it still needs to integrate better with other table data transformation code, it needs to work with variable length arrays, and should be possible to enable/disable on a per-column basis.  Most of this work is progressing in the table-scaling branch but won't be ready for the v3.2 release.
- [ ] NULL/BLANK values in both binary and ASCII tables should be handled sensibly (see https://trac.assembla.com/pyfits/ticket/207)
- [ ] Zero-width (empty) columns should be supported (see https://trac.assembla.com/pyfits/ticket/42)
